fake-ping-bars: 5

tab:
  enabled: true

  update-ticks: 20

  header:
    - ""
    - "&7&l2BUILDERS2TOOLS"
    - ""
    - "&6Plugins config TAB like 2b2t support Folia."
    - ""

  footer:
    - ""
    - "&8%tps% tps - %online% players - %ping% ping"
    - ""